# ----------------------------------------------------------------------------
# A typical developer Config
# ----------------------------------------------------------------------------

config_env_key: {env: PIL_ENV, "dev"}

PIL_DB_USER: {env: PIL_DB_USER, "dxcadmin"}
PIL_DB_PASS: {env: PIL_DB_PASS, "dxc-admin"}
PIL_DB_NAME: {env: PIL_DB_NAME, "pil-engine.cbn8qirdlx7k.us-east-1.rds.amazonaws.com:1521/orcl"}

PROJECT_ROOT: C:\\source_code\\COMSAFE

# Number of processes used to load multiple files
# Use a negative number to dynamically determine the pool size based on server
# CPU, core and threads sizes. E.g. -1 => leave 1 core to the OS
# TODO: Keep for now as example, even though we are not using it right now.
process_pool: -1

# TODO: I don't think any of them is still valid
debug:
    log_progress_after: 20_000
    DISABLED stop_after: 100_000
    enable_reconciliation: False
    new_reconciliation: True

# Define once, and re-use further down
log_dir: "/temp/logs"

my_xxx: {delete:}   # Remove the node
