# ----------------------------------------------------------------------------
# PIL Engine config file
# ----------------------------------------------------------------------------

# Here we expect to find the actual python modules which implement Commission-Nodes.
modules:
    - "{ref:file_configs.git_repo}/commission_nodes"

# Here we expect to find the commission hierachy information
node_structure:
    - "{ref:git.manual_files_git_repo}/Department/ALL/Commission-Hierarchy.xlsx"
    - "{ref:git.manual_files_git_repo}/Department/Direct/Commission-Hierarchy.xlsx"
    - "{ref:git.manual_files_git_repo}/Department/Indirect/Commission-Hierarchy.xlsx"
