# ----------------------------------------------------------------------------
# PIL Engine config file
# ----------------------------------------------------------------------------

version: 1

# Timestamp when the app was started. Is readonly and will never be updated or changed
timestamp: {timestamp: "%Y%m%d-%H%M%S"}

# The env variable for the environment specific config items. E.g. if PIL_CFG = "dev",
# then use config-dev.py to replace specific values in config.py. Very much like "-c" cmdline
# option, PIL_CFG can also be a filename or directory.
# If not configured, "PIL_CFG" is the system default name
# Note: considering the config load process, it's alwways the system default value that will be applied.
config_env_key: {env:PIL_CFG, "PIL_CFG"}

# TODO: Keep for now as example, even though we are not using it right now.
db: "mysql"
database: {import: "./db/{ref:db}_config", {ref:config_env_key}}

git: {import: "./git_config", {ref: config_env_key}}

manual_files: {import: "./manual_files_config", {ref: config_env_key}}

pil: {import: "./pil_config", {ref: config_env_key}}

pipeline: {import: "./pipeline_config", {ref: config_env_key}}

commission_nodes: {import: "./commission_node_config", {ref: config_env_key}}

# Define once, and re-use further down
log_dir: "/temp/logs"
logging: {import: "./logging/logging_config", {ref:config_env_key}}

# TODO: I don't think any of them is still valid
debug:
    log_progress_after: 20_000
    DISABLED stop_after: 100_000
    enable_reconciliation: False
    new_reconciliation: True
