# ----------------------------------------------------------------------------
# PIL Engine config file
# ----------------------------------------------------------------------------


# Files provided by users e.g. via a git repo
ALL:    "{ref:git.manual_files_git_repo}/Department/All/"
DIRECT: "{ref:git.manual_files_git_repo}/Department/Direct/"

category-classifiers":          "{ref:ALL}/ALLENT_REF_CATEGORISECLASSIFIERS.xlsx"
SRNA-pricelist":                "{ref:ALL}/ALLENT_REF_SRNAPRICES.xlsx"
product-catalog":               "{ref:ALL}/**/Product-Catalog.xlsx"
channel-classification":        "{ref:ALL}/ALLENT_REF_CHANNELCLASSIFICATION.xlsx"
multi-dimensional-config-data": "{ref:ALL}/ALLENT_REF_COMLOOKUPDATA.py"
system-config":                 "{ref:ALL}/ALLENT_REF_PILSYSTEMCONFIG.xlsx"
CENT-manual_adjustments":       "{ref:ALL}/ALLENT_REF_MANUALSH.xlsx"
reason-code-pay":               "{ref:ALL}/ALLENT_REF_REASONCODEPAY.xlsx"
manual-file-with-date":         "{ref:ALL}/**/file_123.xlsx"
direct-sh-titles":              "{ref:Direct}/**/DIRENT_REF_SHTITLES.xlsx"
VTS-rev-event-whitelist":       "{ref:ALL}/**/VTS-revenue-event-whitelist.xlsx"
FN-license-price-info":         "{ref:ALL}/**/FN-provision-info.xlsx"
multi-dim-example":             "{ref:ALL}/example-multi-dimensional-data.xlsx"
