# ----------------------------------------------------------------------------
# PIL Engine config file
# ----------------------------------------------------------------------------

version: 1

# Timestamp when the app was started. Is readonly and will never be updated or changed
timestamp: '{timestamp: %Y%m%d-%H%M%S}'

# TODO: Keep for now as example, even though we are not using it right now.
db: "oracle"
database: '{import: "./db/{ref:db}_config.yaml", {ref:config_env_key}}'

git: '{import: "./git_config.yaml", {ref: config_env_key}}'

manual_files: '{import: "./manual_files_config.yaml", {ref: config_env_key}}'

pil: '{import: "./pil_config.yaml", {ref: config_env_key}}'

pipeline: '{import: "./pipeline_config.yaml", {ref: config_env_key}}'

commission_nodes: '{import: "./commission_node_config.yaml", {ref: config_env_key}}'

# Define once, and re-use further down
log_dir: "/temp/logs"
logging: '{import: "./logging/logging_config.yaml", {ref:config_env_key}}'

# TODO: I don't think any of them is still valid
debug:
    log_progress_after: 20_000
    DISABLED stop_after: 100_000
    enable_reconciliation: False
    new_reconciliation: True
