# ----------------------------------------------------------------------------
# PIL Engine config file
# ----------------------------------------------------------------------------


pipeline-directory: "{ref:file_configs.git_repo}/workflows"

# TODO: Not yet implemented
Review-Input:
    task: "pil.tasks.ReviewInputTask"
    depends_on: ""
    config:
        files: "{ref:root_dir}/{ref:args.files}"
        outdir: "{ref:root_dir}/11_input_reviewed"

Sort-Input:
    task: "xxx"
    files: "{ref:root_dir}/11_input_reviewed"
    outdir: "{ref:root_dir}/12_input_sorted"
    memsize: 500_000_000
    depends_on:
        - "Review-Input"

SFoBI to Dremio:
    task: "xxx"
    files: "{ref:root_dir}/12_input_sorted"
    outdir: "{ref:root_dir}/15_dremio"
    commissionPeriod: "{ref:args.commissionPeriod}"
    effectiveDate: "{ref:args.effectiveDate}"
    depends_on:
        - "Sort Input"

"Filter Dummy-Subscriber IDs":
    task: "xxx"
    files: "{ref:root_dir}/12_input_sorted"
    outdir: "{ref:root_dir}/15_dremio"
    timeA: "{ref:args.timeA}"
    depends_on:
        - "SFoBI to Dremio"

"Filter license events":
    task: "pil.tasks.FilterLicenseEventTask"
    files: "{ref:root_dir}/12_input_sorted"
    outdir: "{ref:root_dir}/15_dremio"
    depends_on:
        - "Filter Dummy-Subscriber IDs"

"SFoBI Commission Period ref-data":
    task: "pil.tasks.SFoBIComPeriodRefDataTask",
    depends_on:
        - "Filter license events"
    config:
        files: "{ref:root_dir}/12_input_sorted"
        outdir: "{ref:root_dir}/30_com_periods"
        commissionPeriod: "{ref:args.commissionPeriod}"
        effectiveDate: "{ref:args.effectiveDate}"

"Get manual-files from git-repo":
    outdir: "{ref:root_dir}/30_com_periods"
    commissionPeriod: "{ref:args.commissionPeriod}"
    effectiveDate: "{ref:args.effectiveDate}"
    noPull: "{ref:args.noPull}"
    gitBranch: "{ref:args.gitBranch, 'heads/DEV-1'}"    # Note: {ref:} with default value
    task: "pil.tasks.ManualFilesForComPeriodTask"

"Manual files to CSV":
    files: "{ref:root_dir}/30_com_periods/{ref:com_period}/manual-files/**/*.xlsx"
    outdir: "{ref:root_dir}/30_com_periods/{ref:com_period}"
    commissionPeriod: "{ref:args.commissionPeriod}"
    effectiveDate: "{ref:args.effectiveDate}"
    task: "pil.tasks.ManualFileToCsvTask"
    depends_on: "Get manual-files from git-repo"

"Test Ref-Data in Commission Period folder":
    rootdir: "{ref:root_dir}"
    commissionPeriod: "{ref:args.commissionPeriod}"
    effectiveDate: "{ref:args.effectiveDate}"
    task: "pil.tasks.ComPeriodRefDataTestTask"
    depends_on:
        - "Manual files to CSV"

"Events for Commission Period":
    "files": "{root_dir}/12_input_sorted"
    "outdir": "{root_dir}/30_com_periods"
    "commissionPeriod": "{args.commissionPeriod}"
    "effectiveDate": "{args.effectiveDate}"
    "dummySubscriptionFile": "{root_dir}/15_dremio/MICOS_CONTRACTS_DUMMY_SUBS/**/*.csv"
    "task": "pil.tasks.EventsForComPeriodTask"
    "depends_on": "Test Ref-Data in Commission Period folder"

"Auto-generate lic-events for com-period":
    "files": "{root_dir}/12_input_sorted"
    "outdir": "{root_dir}/30_com_periods"
    "commissionPeriod": "{args.commissionPeriod}"
    "effectiveDate": "{args.effectiveDate}"
    "dummySubscriptionFile": "{root_dir}/15_dremio/MICOS_CONTRACTS_DUMMY_SUBS/**/*.csv"
    "task": "pil.tasks.AutogenerateLicenseEventsForComPeriodTask"
    "depends_on": "Events for Commission Period"

"Auto-generate activation events for com-period":
    "files": "{root_dir}/12_input_sorted"
    "outdir": "{root_dir}/30_com_periods"
    "commissionPeriod": "{args.commissionPeriod}"
    "effectiveDate": "{args.effectiveDate}"
    "dummySubscriptionFile": "{root_dir}/15_dremio/MICOS_CONTRACTS_DUMMY_SUBS/**/*.csv"
    "task": "pil.tasks.AutogenerateActivationEventsForComPeriodTask"
    "depends_on": "Auto-generate lic-events for com-period"

"Ingest Tests":
    "rootdir": "{root_dir}"
    "commissionPeriod": "{args.commissionPeriod}"
    "effectiveDate": "{args.effectiveDate}"
    "task": "pil.tasks.IngestTestTask"
    "depends_on": ["Auto-generate activation events for com-period"]

"CSV to Parquet":
    "files": "{root_dir}/15_dremio"
    "outdir": "{root_dir}/16_parquet"
    "task": "pil.tasks.CsvToParquetTask"
    "depends_on": []
